"""
test_manipulation.py
---------------------
L0 unit tests for the manipulation planning module.

Covers:
  - task_spec_schema: TaskSpec validation, Phase validators, Predicate union types
  - skill_registry: SKILL_REGISTRY contents, is_valid_skill, get_skill, skills_for_prompt
  - client: ContinuityManagerClient / PolicyBankClient URL construction (no I/O)
  - intent_router: manipulation_task intent is now a valid Intent
  - routes cache key determinism
"""
from __future__ import annotations

import json
import time
import uuid
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

pytestmark = pytest.mark.l0

# ---------------------------------------------------------------------------
# Schema imports
# ---------------------------------------------------------------------------
from service.isaac_assist_service.manipulation.task_spec_schema import (
    CompoundPredicate,
    DurationExceededPredicate,
    GripperClosedPredicate,
    HandRole,
    ObjectAttachedPredicate,
    ObjectGraspTarget,
    Phase,
    PhaseConstraints,
    PhaseTelemetry,
    PlanRequest,
    PlaceOnObjectTarget,
    Pose,
    PredicateType,
    ReplanRequest,
    SceneObject,
    SceneSnapshot,
    TaskSpec,
)

# ---------------------------------------------------------------------------
# Registry imports
# ---------------------------------------------------------------------------
from service.isaac_assist_service.manipulation.skill_registry import (
    SKILL_NAMES,
    SKILL_REGISTRY,
    get_skill,
    is_valid_skill,
    skills_for_prompt,
)


# ---------------------------------------------------------------------------
# Helpers: minimal valid TaskSpec builders
# ---------------------------------------------------------------------------

def _pose(x=0.5, y=0.0, z=0.8):
    return Pose(position=[x, y, z], quaternion=[0.0, 0.0, 0.0, 1.0])


def _snapshot(*object_ids):
    return SceneSnapshot(
        timestamp=time.time(),
        objects=[
            SceneObject(
                object_id=oid,
                **{"class": "rigid"},
                pose=_pose(),
                bbox_3d=[0.05, 0.05, 0.05],
                confidence=0.95,
            )
            for oid in object_ids
        ],
    )


def _pick_place_spec(mug_id="mug_01", tray_id="tray_01") -> TaskSpec:
    snap = _snapshot(mug_id, tray_id)
    return TaskSpec(
        goal_text="Pick up the mug and place it on the tray",
        embodiment_id="tenthings_v1_open_arm_bimanual",
        scene_snapshot=snap,
        phases=[
            Phase(
                phase_index=0,
                skill_name="pick_rigid",
                hand_assignment={"right": HandRole.LEAD, "left": HandRole.IDLE},
                semantic_target=ObjectGraspTarget(type="object_grasp", object_id=mug_id),
                success_predicate=ObjectAttachedPredicate(
                    type="object_attached", object_id=mug_id, arm="right"
                ),
                failure_predicate=DurationExceededPredicate(
                    type="duration_exceeded", threshold_s=10.0
                ),
            ),
            Phase(
                phase_index=1,
                skill_name="place_on_surface",
                hand_assignment={"right": HandRole.LEAD, "left": HandRole.IDLE},
                semantic_target=PlaceOnObjectTarget(
                    type="place_on_object",
                    carry_object_id=mug_id,
                    support_object_id=tray_id,
                ),
                success_predicate=CompoundPredicate(
                    type="AND",
                    clauses=[
                        GripperClosedPredicate(type="gripper_closed", arm="right"),
                    ],
                ),
                failure_predicate=DurationExceededPredicate(
                    type="duration_exceeded", threshold_s=12.0
                ),
            ),
        ],
    )


# ===========================================================================
# TaskSpec schema tests
# ===========================================================================

class TestTaskSpecValidation:

    def test_minimal_valid_spec(self):
        spec = _pick_place_spec()
        assert spec.spec_version == "1.0"
        assert len(spec.phases) == 2

    def test_task_id_autogenerated(self):
        spec = _pick_place_spec()
        assert len(spec.task_id) == 36  # UUID4 string

    def test_contiguous_phase_indices_required(self):
        with pytest.raises(Exception):  # pydantic ValidationError
            snap = _snapshot("obj1")
            TaskSpec(
                goal_text="test",
                scene_snapshot=snap,
                phases=[
                    Phase(
                        phase_index=0,
                        skill_name="pick_rigid",
                        hand_assignment={"right": HandRole.LEAD, "left": HandRole.IDLE},
                        semantic_target=ObjectGraspTarget(type="object_grasp", object_id="obj1"),
                        success_predicate=ObjectAttachedPredicate(
                            type="object_attached", object_id="obj1", arm="right"
                        ),
                        failure_predicate=DurationExceededPredicate(
                            type="duration_exceeded", threshold_s=5.0
                        ),
                    ),
                    Phase(
                        phase_index=2,  # skipped index 1 → invalid
                        skill_name="place_on_surface",
                        hand_assignment={"right": HandRole.LEAD, "left": HandRole.IDLE},
                        semantic_target=ObjectGraspTarget(type="object_grasp", object_id="obj1"),
                        success_predicate=DurationExceededPredicate(
                            type="duration_exceeded", threshold_s=1.0
                        ),
                        failure_predicate=DurationExceededPredicate(
                            type="duration_exceeded", threshold_s=5.0
                        ),
                    ),
                ],
            )

    def test_unknown_object_id_rejected(self):
        with pytest.raises(Exception):
            snap = _snapshot("obj1")   # only obj1 in scene
            TaskSpec(
                goal_text="test",
                scene_snapshot=snap,
                phases=[
                    Phase(
                        phase_index=0,
                        skill_name="pick_rigid",
                        hand_assignment={"right": HandRole.LEAD, "left": HandRole.IDLE},
                        semantic_target=ObjectGraspTarget(
                            type="object_grasp",
                            object_id="ghost_obj",  # not in scene → invalid
                        ),
                        success_predicate=DurationExceededPredicate(
                            type="duration_exceeded", threshold_s=1.0
                        ),
                        failure_predicate=DurationExceededPredicate(
                            type="duration_exceeded", threshold_s=5.0
                        ),
                    )
                ],
            )

    def test_phase_requires_exactly_one_lead(self):
        with pytest.raises(Exception):
            snap = _snapshot("obj1")
            Phase(
                phase_index=0,
                skill_name="pick_rigid",
                hand_assignment={"right": HandRole.LEAD, "left": HandRole.LEAD},  # two leads
                semantic_target=ObjectGraspTarget(type="object_grasp", object_id="obj1"),
                success_predicate=DurationExceededPredicate(
                    type="duration_exceeded", threshold_s=1.0
                ),
                failure_predicate=DurationExceededPredicate(
                    type="duration_exceeded", threshold_s=5.0
                ),
            )

    def test_phase_with_no_lead_rejected(self):
        with pytest.raises(Exception):
            Phase(
                phase_index=0,
                skill_name="pick_rigid",
                hand_assignment={"right": HandRole.IDLE, "left": HandRole.IDLE},  # no lead
                semantic_target=ObjectGraspTarget(type="object_grasp", object_id="x"),
                success_predicate=DurationExceededPredicate(
                    type="duration_exceeded", threshold_s=1.0
                ),
                failure_predicate=DurationExceededPredicate(
                    type="duration_exceeded", threshold_s=5.0
                ),
            )

    def test_empty_phases_rejected(self):
        with pytest.raises(Exception):
            TaskSpec(
                goal_text="test",
                scene_snapshot=_snapshot("obj1"),
                phases=[],
            )

    def test_model_serializes_to_json(self):
        spec = _pick_place_spec()
        raw = spec.model_dump_json()
        parsed = json.loads(raw)
        assert parsed["spec_version"] == "1.0"
        assert len(parsed["phases"]) == 2

    def test_model_roundtrip(self):
        spec = _pick_place_spec()
        restored = TaskSpec.model_validate(spec.model_dump())
        assert restored.goal_text == spec.goal_text
        assert len(restored.phases) == len(spec.phases)

    def test_compound_predicate_and(self):
        pred = CompoundPredicate(
            type="AND",
            clauses=[
                GripperClosedPredicate(type="gripper_closed", arm="right"),
                ObjectAttachedPredicate(type="object_attached", object_id="x", arm="right"),
            ],
        )
        assert pred.type == "AND"
        assert len(pred.clauses) == 2

    def test_nested_compound_predicate(self):
        inner = CompoundPredicate(
            type="OR",
            clauses=[
                DurationExceededPredicate(type="duration_exceeded", threshold_s=5.0),
            ],
        )
        outer = CompoundPredicate(type="AND", clauses=[inner])
        assert outer.type == "AND"


class TestPlanRequest:

    def test_minimal_plan_request(self):
        req = PlanRequest(goal_text="pick up the mug")
        assert req.scene_snapshot is None
        assert req.prior_attempt is None

    def test_plan_request_with_snapshot(self):
        snap = _snapshot("mug_01")
        req = PlanRequest(goal_text="pick up the mug", scene_snapshot=snap)
        assert len(req.scene_snapshot.objects) == 1

    def test_replan_request(self):
        req = ReplanRequest(
            task_id=str(uuid.uuid4()),
            current_phase=1,
            failure_reason="object_lost: mug_01 not detected for 15 frames",
        )
        assert req.current_phase == 1
        assert req.scene_snapshot is None


class TestPhaseTelemetry:

    def test_success_telemetry(self):
        t = PhaseTelemetry(
            task_id="t1",
            goal_text="pick up mug",
            phase_index=0,
            skill_name="pick_rigid",
            outcome="success",
            duration_s=3.2,
            ft_peak_n=8.1,
        )
        assert t.failure_reason is None
        assert t.outcome == "success"

    def test_fail_telemetry_with_reason(self):
        t = PhaseTelemetry(
            task_id="t1",
            goal_text="fold cloth",
            phase_index=2,
            skill_name="bimanual_fold",
            outcome="fail",
            failure_reason="max_duration exceeded: 12s > 10s",
        )
        assert t.failure_reason is not None

    def test_telemetry_outcome_enum(self):
        with pytest.raises(Exception):
            PhaseTelemetry(
                task_id="t1",
                goal_text="test",
                phase_index=0,
                skill_name="pick_rigid",
                outcome="invalid_outcome",  # not in Literal
            )


# ===========================================================================
# Skill registry tests
# ===========================================================================

class TestSkillRegistry:

    def test_eleven_skills_registered(self):
        assert len(SKILL_REGISTRY) == 11

    def test_all_known_skills_present(self):
        expected = {
            "pick_rigid", "pick_deformable", "place_on_surface",
            "transit_to_pose", "push_object", "press_button", "open_drawer",
            "stabilize_object", "hold_cloth_taut",
            "bimanual_handover", "bimanual_fold",
        }
        assert set(SKILL_REGISTRY.keys()) == expected

    def test_skill_names_sorted(self):
        assert SKILL_NAMES == sorted(SKILL_NAMES)

    def test_is_valid_skill_true(self):
        assert is_valid_skill("pick_rigid")
        assert is_valid_skill("bimanual_fold")

    def test_is_valid_skill_false(self):
        assert not is_valid_skill("unknown_skill")
        assert not is_valid_skill("")

    def test_get_skill_known(self):
        spec = get_skill("pick_rigid")
        assert spec.name == "pick_rigid"
        assert spec.arm_mode == "single"

    def test_get_skill_unknown_raises(self):
        with pytest.raises(KeyError):
            get_skill("nonexistent_skill")

    def test_assist_skills_have_assist_role(self):
        for name in ("stabilize_object", "hold_cloth_taut"):
            spec = get_skill(name)
            assert spec.assist_role is True

    def test_bimanual_skills_are_bimanual_sync(self):
        for name in ("bimanual_handover", "bimanual_fold"):
            spec = get_skill(name)
            assert spec.arm_mode == "bimanual_sync"

    def test_skills_for_prompt_contains_all_names(self):
        text = skills_for_prompt()
        for name in SKILL_NAMES:
            assert name in text

    def test_skills_for_prompt_is_multiline(self):
        assert "\n" in skills_for_prompt()

    def test_all_skills_have_description(self):
        for name, spec in SKILL_REGISTRY.items():
            assert spec.description, f"'{name}' has empty description"

    def test_single_arm_skills_have_no_assist_role(self):
        for name in ("pick_rigid", "pick_deformable", "place_on_surface",
                     "transit_to_pose", "push_object", "press_button", "open_drawer"):
            assert not get_skill(name).assist_role


# ===========================================================================
# Client URL construction (no I/O)
# ===========================================================================

class TestClientConstruction:

    def test_cm_client_uses_config_url(self):
        from service.isaac_assist_service.manipulation.client import ContinuityManagerClient
        from service.isaac_assist_service.config import config

        client = ContinuityManagerClient()
        assert client.base_url == config.continuity_manager_url.rstrip("/")

    def test_pb_client_uses_config_url(self):
        from service.isaac_assist_service.manipulation.client import PolicyBankClient
        from service.isaac_assist_service.config import config

        client = PolicyBankClient()
        assert client.base_url == config.policy_bank_url.rstrip("/")

    def test_cm_client_accepts_custom_url(self):
        from service.isaac_assist_service.manipulation.client import ContinuityManagerClient

        client = ContinuityManagerClient("http://custom-host:9999")
        assert client.base_url == "http://custom-host:9999"


# ===========================================================================
# Intent router: manipulation_task is a valid intent
# ===========================================================================

class TestManipulationIntent:

    def test_manipulation_task_in_intent_examples(self):
        from service.isaac_assist_service.chat.intent_router import INTENT_EXAMPLES
        manipulation_examples = [
            (msg, intent)
            for msg, intent in INTENT_EXAMPLES
            if intent == "manipulation_task"
        ]
        assert len(manipulation_examples) >= 3

    def test_intent_system_mentions_manipulation_task(self):
        from service.isaac_assist_service.chat.intent_router import INTENT_SYSTEM
        assert "manipulation_task" in INTENT_SYSTEM

    def test_manipulation_task_is_valid_intent_type(self):
        """manipulation_task is a valid Literal value for Intent."""
        from service.isaac_assist_service.chat.intent_router import Intent
        from typing import get_args
        valid = get_args(Intent)
        assert "manipulation_task" in valid


# ===========================================================================
# Config: manipulation fields present
# ===========================================================================

class TestManipulationConfig:

    def test_continuity_manager_url_defaults(self):
        from service.isaac_assist_service.config import config
        assert config.continuity_manager_url.startswith("http")

    def test_policy_bank_url_defaults(self):
        from service.isaac_assist_service.config import config
        assert config.policy_bank_url.startswith("http")

    def test_embodiment_id_nonempty(self):
        from service.isaac_assist_service.config import config
        assert config.manipulation_embodiment_id


# ===========================================================================
# Routes: cache key is deterministic
# ===========================================================================

class TestRoutesCacheKey:

    def test_same_goal_same_key(self):
        from service.isaac_assist_service.manipulation.routes import _cache_key
        snap = _snapshot("obj1")
        assert _cache_key("pick up the mug", snap) == _cache_key("pick up the mug", snap)

    def test_different_goal_different_key(self):
        from service.isaac_assist_service.manipulation.routes import _cache_key
        snap = _snapshot("obj1")
        assert _cache_key("pick up the mug", snap) != _cache_key("fold the cloth", snap)

    def test_no_snapshot_returns_key(self):
        from service.isaac_assist_service.manipulation.routes import _cache_key
        key = _cache_key("test goal", None)
        assert isinstance(key, str) and len(key) == 64  # SHA-256 hex
