"""User-facing one-line descriptions of every tool handler.

Generated by ``scripts/regenerate_descriptions.py`` from
``tool_executor.py``. Hand overrides go in ``_OVERRIDES`` — those win
over the generated ones.

Voice: short, plain, written for a robotics engineer watching the agent
work. NOT written for an LLM that needs to call the tool. ~10-15 words.

The orchestrator looks each one up via :func:`describe` and embeds the
result in ``tool_call_started`` SSE events so the UI can show it as a
tooltip subtitle on the verb label.
"""
from __future__ import annotations

from typing import Dict

# ── Generated (do not hand-edit; use _OVERRIDES) ────────────────────────
# This dict is populated by scripts/regenerate_descriptions.py. Until
# that runs, it's empty — describe() returns "" and the UI tooltip
# falls back to the function signature only. Safe no-op default.
_GENERATED: Dict[str, str] = {}

# ── Hand overrides (these win) ──────────────────────────────────────────
# Add entries here as you spot bad generated descriptions in the UI.
# These are preserved verbatim by the regenerator.
_OVERRIDES: Dict[str, str] = {}


def describe(tool_name: str) -> str:
    """Return the one-line description for this tool, or ``""`` if unknown."""
    return _OVERRIDES.get(tool_name) or _GENERATED.get(tool_name, "")
