"""Tool name → present-progressive verb phrase for the live UI strip.

The agent's tool registry has hundreds of handlers. We auto-derive a
verb from the function name (``create_prim`` → ``Creating prim``)
using a conjugation table for the first segment, with a manual
override file for the awkward cases (``run_usd_script`` →
``Running USD script``).

Tells the user what is happening, not what the tool is called. Function
name + args still flow through tooltips for engineers who want them.
"""
from __future__ import annotations

from typing import Dict

# Verb-stem conjugations. Auto-applied to tool names whose first
# underscore-separated segment matches.
_CONJUGATION: Dict[str, str] = {
    "activate": "Activating",
    "add": "Adding",
    "analyze": "Analyzing",
    "anchor": "Anchoring",
    "apply": "Applying",
    "approve": "Approving",
    "assemble": "Assembling",
    "assign": "Assigning",
    "batch": "Batch processing",
    "build": "Building",
    "bulk": "Bulk applying",
    "calibrate": "Calibrating",
    "cancel": "Cancelling",
    "capture": "Capturing",
    "catalog": "Cataloguing",
    "check": "Checking",
    "checkpoint": "Checkpointing",
    "clone": "Cloning",
    "cloud": "Cloud action",
    "compare": "Comparing",
    "compute": "Computing",
    "configure": "Configuring",
    "connect": "Connecting",
    "console": "Reading console",
    "count": "Counting",
    "create": "Creating",
    "debug": "Debugging",
    "define": "Defining",
    "delete": "Removing",
    "detect": "Detecting",
    "diagnose": "Diagnosing",
    "disable": "Disabling",
    "dispatch": "Dispatching",
    "download": "Downloading",
    "duplicate": "Duplicating",
    "edit": "Editing",
    "enable": "Enabling",
    "enforce": "Enforcing",
    "evaluate": "Evaluating",
    "execute": "Executing",
    "explain": "Explaining",
    "export": "Exporting",
    "extract": "Extracting",
    "filter": "Filtering",
    "find": "Finding",
    "finetune": "Fine-tuning",
    "fix": "Fixing",
    "flatten": "Flattening",
    "focus": "Focusing",
    "generate": "Generating",
    "get": "Reading",
    "grasp": "Grasping",
    "group": "Grouping",
    "hardware": "Checking hardware",
    "highlight": "Highlighting",
    "import": "Importing",
    "inspect": "Inspecting",
    "interpolate": "Interpolating",
    "iterate": "Iterating",
    "launch": "Launching",
    "list": "Listing",
    "load": "Loading",
    "lookup": "Looking up",
    "measure": "Measuring",
    "merge": "Merging",
    "monitor": "Monitoring",
    "move": "Moving",
    "navigate": "Navigating",
    "nucleus": "Browsing Nucleus",
    "open": "Opening",
    "optimize": "Optimizing",
    "overlap": "Checking overlap",
    "pause": "Pausing",
    "pixel": "Mapping pixel",
    "plan": "Planning",
    "play": "Playing",
    "post": "Posting",
    "preflight": "Pre-flighting",
    "preview": "Previewing",
    "prim": "Reading prim",
    "proactive": "Checking",
    "profile": "Profiling",
    "publish": "Publishing",
    "query": "Querying",
    "queue": "Queueing",
    "quick": "Quick action",
    "raycast": "Raycasting",
    "record": "Recording",
    "redact": "Redacting",
    "remove": "Removing",
    "render": "Rendering",
    "replay": "Replaying",
    "restore": "Restoring",
    "review": "Reviewing",
    "robot": "Robot wizard",
    "ros2": "ROS2 call",
    "run": "Running",
    "save": "Saving",
    "scatter": "Scattering",
    "scene": "Reading scene",
    "select": "Selecting",
    "set": "Setting",
    "setup": "Setting up",
    "show": "Showing",
    "simplify": "Simplifying",
    "sim": "Simulating",
    "slash": "Slash command",
    "solve": "Solving",
    "start": "Starting",
    "stop": "Stopping",
    "suggest": "Suggesting",
    "summarize": "Summarizing",
    "sweep": "Sweeping",
    "teach": "Teaching",
    "teleop": "Teleop",
    "teleport": "Teleporting",
    "trace": "Tracing",
    "train": "Training",
    "tune": "Tuning",
    "update": "Updating",
    "upload": "Uploading",
    "validate": "Validating",
    "verify": "Verifying",
    "vision": "Vision",
    "visualize": "Visualizing",
    "watch": "Watching",
}

# Manual overrides for awkward auto-derived names. Add as you spot them.
_OVERRIDES: Dict[str, str] = {
    "run_usd_script": "Running USD script",
    "queue_exec_patch": "Applying patch",
    "exec_sync": "Executing on Kit",
    "lookup_knowledge": "Looking up reference",
    "lookup_product_spec": "Looking up product spec",
    "lookup_material": "Looking up material",
    "lookup_api_deprecation": "Checking API deprecation",
    "scatter_on_surface": "Scattering objects",
    "scene_summary": "Summarizing scene",
    "scene_diff": "Diffing scene",
    "scene_aware_starter_prompts": "Suggesting prompts",
    "get_viewport_image": "Capturing viewport",
    "capture_viewport": "Capturing viewport",
    "capture_camera_image": "Capturing camera",
    "create_prim": "Creating prim",
    "delete_prim": "Removing prim",
    "apply_physics_material": "Applying physics material",
    "apply_api_schema": "Applying API schema",
    "apply_dr_preset": "Applying randomization",
    "set_attribute": "Setting attribute",
    "get_attribute": "Reading attribute",
    "robot_wizard": "Running robot wizard",
    "ros2_publish": "ROS2 publishing",
    "ros2_subscribe_once": "ROS2 subscribing",
    "preflight_check": "Pre-flight check",
    "diagnose_physics_error": "Diagnosing physics",
    "diagnose_training": "Diagnosing training",
    "diagnose_domain_gap": "Diagnosing domain gap",
    "find_prims_by_name": "Finding prims",
    "find_prims_by_schema": "Finding prims",
    "list_all_prims": "Listing prims",
    "build_stage_index": "Indexing stage",
    "save_delta_snapshot": "Saving snapshot",
    "restore_delta_snapshot": "Restoring snapshot",
    "compute_convex_hull": "Computing hull",
    "set_camera_look_at": "Aiming camera",
    "set_viewport_camera": "Switching camera",
    "load_groot_policy": "Loading policy",
    "evaluate_groot": "Evaluating policy",
    "finetune_groot": "Fine-tuning policy",
    "ros2_list_nodes": "Listing ROS2 nodes",
    "ros2_list_topics": "Listing ROS2 topics",
    "ros2_list_services": "Listing ROS2 services",
    "ros2_get_topic_type": "Reading ROS2 topic type",
    "ros2_get_message_type": "Reading ROS2 msg type",
    "ros2_get_node_details": "Reading ROS2 node",
    "ros2_call_service": "Calling ROS2 service",
    "configure_ros2_bridge": "Configuring ROS2 bridge",
    "configure_ros2_time": "Configuring ROS2 time",
    "setup_ros2_bridge": "Setting up ROS2 bridge",
    "iterate_reward": "Iterating reward",
    "review_reward": "Reviewing reward",
    "evaluate_reward": "Evaluating reward",
    "generate_reward": "Generating reward",
    "play_animation": "Playing animation",
    "set_keyframe": "Setting keyframe",
    "list_keyframes": "Listing keyframes",
    "publish_robot_description": "Publishing URDF",
    "generate_robot_description": "Generating URDF",
    "import_robot": "Importing robot",
    "verify_import": "Verifying import",
    "load_payload": "Loading payload",
    "list_payloads": "Listing payloads",
    "list_references": "Listing references",
    "add_reference": "Adding reference",
    "add_usd_reference": "Adding USD reference",
    "add_sublayer": "Adding sublayer",
    "list_layers": "Listing layers",
    "set_edit_target": "Setting edit target",
    "flatten_layers": "Flattening layers",
    "set_environment_background": "Setting background",
    "create_hdri_skydome": "Creating skydome",
    "add_default_light": "Adding default light",
    "set_light_color": "Setting light color",
    "set_light_intensity": "Setting light intensity",
    "list_lights": "Listing lights",
    "get_light_properties": "Reading light",
}


def verb_for(tool_name: str) -> str:
    """Return the present-progressive phrase to display for this tool."""
    if not tool_name:
        return ""
    if tool_name in _OVERRIDES:
        return _OVERRIDES[tool_name]
    parts = tool_name.split("_")
    if not parts:
        return tool_name
    head = parts[0].lower()
    rest = " ".join(parts[1:])
    if head in _CONJUGATION:
        return f"{_CONJUGATION[head]} {rest}".rstrip()
    return tool_name.replace("_", " ").capitalize()
