"""Regenerate descriptions.py from the current tool_executor.py.

Diff-aware: only calls the LLM for tools that are NEW or MISSING from the
existing ``_GENERATED`` dict. Existing entries are kept. ``_OVERRIDES`` is
never touched. Safe to run as a pre-commit hook.

Provider auto-detect (preference order):
  1. ``GEMINI_API_KEY``  → google-genai SDK (cheap, fast — recommended)
  2. ``ANTHROPIC_API_KEY`` → anthropic SDK
  Force one when both are set:  ``PROVIDER=gemini`` or ``PROVIDER=anthropic``
  Override model:  ``REGEN_GEMINI_MODEL=...`` or ``REGEN_ANTHROPIC_MODEL=...``

Usage:
    python scripts/regenerate_descriptions.py             # incremental
    python scripts/regenerate_descriptions.py --rebuild   # regenerate all
    python scripts/regenerate_descriptions.py --dry-run   # show what would change
"""
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
from pathlib import Path
from typing import Dict

ROOT = Path(__file__).resolve().parents[1]
TOOL_EXECUTOR = ROOT / "service" / "isaac_assist_service" / "chat" / "tools" / "tool_executor.py"
DESCRIPTIONS = ROOT / "service" / "isaac_assist_service" / "chat" / "tools" / "descriptions.py"

PROMPT_TEMPLATE = """You are documenting tool handlers for a robotics simulation assistant UI.

Each handler appears below with its function name and source. For each one, write ONE LINE (10-15 words, max 100 chars) that describes what the tool does FROM A USER'S PERSPECTIVE.

Voice rules:
- Plain English. Avoid USD/jargon unless unavoidable.
- Active verb. Start with "Adds...", "Reads...", "Configures...", etc.
- No parameter lists, no implementation detail.
- A robotics engineer watching the agent work should understand it instantly.

Return ONLY a JSON object {{"tool_name": "description", ...}}. No prose, no markdown fences.

Tools:
{tools_block}
"""


def extract_handlers(source: str) -> Dict[str, str]:
    """Parse tool_executor.py and return {tool_name: source_snippet}.

    Tools are exposed as ``async def _handle_<name>`` functions. Snippet
    is the signature plus the first ~14 lines of the body — enough for
    Claude to summarise without dumping the entire handler.
    """
    tree = ast.parse(source)
    handlers: Dict[str, str] = {}
    src_lines = source.splitlines()
    for node in ast.walk(tree):
        if isinstance(node, (ast.AsyncFunctionDef, ast.FunctionDef)):
            name = node.name
            if name.startswith("_handle_"):
                tool_name = name[len("_handle_") :]
                start = node.lineno - 1
                end = min(start + 14, len(src_lines))
                handlers[tool_name] = "\n".join(src_lines[start:end])
    return handlers


def load_existing_descriptions() -> Dict[str, str]:
    if not DESCRIPTIONS.exists():
        return {}
    src = DESCRIPTIONS.read_text(encoding="utf-8")
    m = re.search(r"_GENERATED:\s*Dict\[str,\s*str\]\s*=\s*(\{.*?\n\})", src, re.S)
    if not m:
        return {}
    try:
        return ast.literal_eval(m.group(1))
    except Exception:
        return {}


def write_descriptions(generated: Dict[str, str]) -> None:
    """Rewrite descriptions.py preserving _OVERRIDES section verbatim."""
    overrides_block = "_OVERRIDES: Dict[str, str] = {}"
    if DESCRIPTIONS.exists():
        existing = DESCRIPTIONS.read_text(encoding="utf-8")
        m = re.search(r"(_OVERRIDES:\s*Dict\[str,\s*str\]\s*=\s*\{[^}]*\})", existing, re.S)
        if m:
            overrides_block = m.group(1)

    body_lines = ["_GENERATED: Dict[str, str] = {"]
    for k in sorted(generated):
        v = generated[k].replace("\\", "\\\\").replace('"', '\\"')
        body_lines.append(f'    "{k}": "{v}",')
    body_lines.append("}")
    generated_block = "\n".join(body_lines)

    out = f'''"""User-facing one-line descriptions of every tool handler.

Generated by ``scripts/regenerate_descriptions.py`` from
``tool_executor.py``. Hand overrides go in ``_OVERRIDES`` — those win
over the generated ones.

Voice: short, plain, written for a robotics engineer watching the agent
work. NOT written for an LLM that needs to call the tool. ~10-15 words.
"""
from __future__ import annotations

from typing import Dict

# ── Generated (do not hand-edit; use _OVERRIDES) ────────────────────────
{generated_block}

# ── Hand overrides (these win) ──────────────────────────────────────────
{overrides_block}


def describe(tool_name: str) -> str:
    """Return the one-line description for this tool, or ``""`` if unknown."""
    return _OVERRIDES.get(tool_name) or _GENERATED.get(tool_name, "")
'''
    DESCRIPTIONS.write_text(out, encoding="utf-8")


def _make_caller():
    """Auto-detect available LLM provider and return (call_fn, model_name).

    Preference order: GEMINI_API_KEY → google-genai (cheap, fast),
    then ANTHROPIC_API_KEY → anthropic (fallback). Whichever you have
    set wins — no flag needed for the common case.

    The user can force a specific provider via PROVIDER=gemini|anthropic
    if both are set.
    """
    forced = os.environ.get("PROVIDER", "").lower()

    def _try_gemini():
        try:
            from google import genai
        except ImportError:
            print("ERROR: google-genai SDK not installed. `pip install google-genai`.",
                  file=sys.stderr)
            sys.exit(1)
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            print("ERROR: GEMINI_API_KEY not set.", file=sys.stderr)
            sys.exit(1)
        # Use the same model the FastAPI service uses by default. Override
        # via REGEN_GEMINI_MODEL if you want something cheaper/different.
        model = os.environ.get("REGEN_GEMINI_MODEL", "gemini-2.5-flash")
        client = genai.Client(api_key=api_key)

        def call(prompt: str) -> str:
            r = client.models.generate_content(model=model, contents=prompt)
            return (r.text or "").strip()

        return call, model

    def _try_anthropic():
        try:
            import anthropic
        except ImportError:
            print("ERROR: anthropic SDK not installed. `pip install anthropic`.",
                  file=sys.stderr)
            sys.exit(1)
        if not os.environ.get("ANTHROPIC_API_KEY"):
            print("ERROR: ANTHROPIC_API_KEY not set.", file=sys.stderr)
            sys.exit(1)
        client = anthropic.Anthropic()
        model = os.environ.get("REGEN_ANTHROPIC_MODEL", "claude-opus-4-7")

        def call(prompt: str) -> str:
            msg = client.messages.create(
                model=model,
                max_tokens=2048,
                messages=[{"role": "user", "content": prompt}],
            )
            return (msg.content[0].text or "").strip()

        return call, model

    if forced == "gemini":
        return _try_gemini()
    if forced == "anthropic":
        return _try_anthropic()
    if os.environ.get("GEMINI_API_KEY"):
        return _try_gemini()
    if os.environ.get("ANTHROPIC_API_KEY"):
        return _try_anthropic()
    print(
        "ERROR: no LLM provider configured. Set GEMINI_API_KEY or "
        "ANTHROPIC_API_KEY (or pass PROVIDER=gemini|anthropic).",
        file=sys.stderr,
    )
    sys.exit(1)


def call_llm_batched(handlers_to_doc: Dict[str, str], batch_size: int = 30) -> Dict[str, str]:
    call, model_name = _make_caller()
    print(f"  using model: {model_name}", file=sys.stderr)
    out: Dict[str, str] = {}
    items = list(handlers_to_doc.items())
    n_batches = (len(items) + batch_size - 1) // batch_size
    for i in range(0, len(items), batch_size):
        batch = items[i : i + batch_size]
        block = "\n\n".join(f"### {name}\n```python\n{src}\n```" for name, src in batch)
        print(f"  batch {i // batch_size + 1}/{n_batches} ({len(batch)} tools)...",
              file=sys.stderr)
        text = call(PROMPT_TEMPLATE.format(tools_block=block))
        # Strip code fences if the model added them despite instructions.
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```\s*$", "", text)
        try:
            parsed = json.loads(text)
            out.update(parsed)
        except json.JSONDecodeError:
            print(f"WARN: batch {i // batch_size + 1} returned invalid JSON, skipping",
                  file=sys.stderr)
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rebuild", action="store_true",
                    help="Regenerate ALL descriptions, not just missing ones")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print what would be regenerated; don't call the LLM or write files")
    args = ap.parse_args()

    handlers = extract_handlers(TOOL_EXECUTOR.read_text(encoding="utf-8"))
    existing = {} if args.rebuild else load_existing_descriptions()
    missing = {k: v for k, v in handlers.items() if k not in existing}

    print(f"Found {len(handlers)} handler(s) in tool_executor.py.")
    print(f"Existing descriptions: {len(existing)}")
    print(f"Missing: {len(missing)}")

    if args.dry_run:
        if missing:
            print("\nWould generate descriptions for:")
            for k in sorted(missing)[:20]:
                print(f"  - {k}")
            if len(missing) > 20:
                print(f"  ... and {len(missing) - 20} more")
        return

    if not missing:
        print("Up to date — no changes needed.")
        return

    print(f"\nGenerating {len(missing)} new description(s)...")
    new = call_llm_batched(missing)
    merged = {**existing, **new}
    # Drop entries for tools that no longer exist
    merged = {k: v for k, v in merged.items() if k in handlers}

    write_descriptions(merged)
    print(f"\nWrote {len(merged)} descriptions to {DESCRIPTIONS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
